### ISSUE TITLE
setStrom fehlender Prototyp und falsch deklariert. 

### ISSUE THREAD

**Issue by pkahlert** [BHTes16/ecarui#13]
setStrom kann keinen Char erwarten wenn das ISOCMS ein 24Bit Wert liefert.
Vorschlag uint32_t nutzen und dann einfach 8 Bit wegschmeißen.

**Comment by lt1-** [comment]
Im zweifel immer 64bit doubles :)

**Comment by 7be** [comment]
welche 8 weg?
